FROM php:7.4-fpm-alpine3.11

RUN curl -sS "https://getcomposer.org/installer" | php -- --install-dir=/usr/local/bin --filename=composer
# RUN composer global require hirak/prestissimo

#include(alpine-developer.docker)
#include(bobash.docker)
